### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by berdario** [hasankhan/sql-cli#11] opened 2015-05-01 17:50 UTC
```
Connecting to 10.129.121.67...events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at Connection.emit (events.js:143:13)
    at Parser.<anonymous> (/tmp/a/sql-cli/node_modules/mssql/node_modules/tedious/lib/connection.js:637:15)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:166:7)
    at Parser.nextToken (/tmp/a/sql-cli/node_modules/mssql/node_modules/tedious/lib/token/token-stream-parser.js:102:14)
    at Parser.addBuffer (/tmp/a/sql-cli/node_modules/mssql/node_modules/tedious/lib/token/token-stream-parser.js:68:17)
    at Connection.sendDataToTokenStreamParser (/tmp/a/sql-cli/node_modules/mssql/node_modules/tedious/lib/connection.js:891:35)
    at Connection.STATE.SENT_LOGIN7_WITH_STANDARD_LOGIN.events.data (/tmp/a/sql-cli/node_modules/mssql/node_modules/tedious/lib/connection.js:176:23)
    at Connection.dispatchEvent (/tmp/a/sql-cli/node_modules/mssql/node_modules/tedious/lib/connection.js:752:59)
```

Tested both with sql-cli from npm and with the dev branch

**Comment by berdario** [comment] 2015-05-01 17:54
Uhm, this is a bit weird, the only `*events.js` I can find is `node_modules/htmlparser2/test/01-events.js`

**Comment by hasankhan** [comment] 2016-10-23 18:36
Code has significantly changed since this was reported also the library is now updated. Closing it, feel free to re-open if the issue is still reproducible with latest release.

**Closed by hasankhan** 2016-10-23 18:36 UTC
